from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class WorkbenchState(StrEnum):
    EMPTY = "EMPTY"
    DRAFT = "DRAFT"
    DRAFT_DIRTY = "DRAFT_DIRTY"
    VALIDATED = "VALIDATED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"
    ERROR = "ERROR"


class ValidationSeverity(StrEnum):
    ERROR = "Error"
    WARNING = "Warning"
    INFORMATION = "Information"


class FillState(StrEnum):
    EMPTY_NO_INTERFACE = "EMPTY_NO_INTERFACE"
    FILLING_VISIBLE = "FILLING_VISIBLE"
    PARTIAL_VISIBLE = "PARTIAL_VISIBLE"
    FULL_NO_INTERFACE = "FULL_NO_INTERFACE"
    DRAINING_VISIBLE = "DRAINING_VISIBLE"
    FULL_WITH_FOAM = "FULL_WITH_FOAM"
    FOAMING_VISIBLE = "FOAMING_VISIBLE"
    UNKNOWN_REVIEW = "UNKNOWN_REVIEW"


class InitialObservationState(StrEnum):
    AUTO = "AUTO"
    EMPTY_NO_INTERFACE = "EMPTY_NO_INTERFACE"
    FILLING_VISIBLE = "FILLING_VISIBLE"
    PARTIAL_VISIBLE = "PARTIAL_VISIBLE"
    FULL_NO_INTERFACE = "FULL_NO_INTERFACE"
    DRAINING_VISIBLE = "DRAINING_VISIBLE"
    FULL_WITH_FOAM = "FULL_WITH_FOAM"
    FOAMING_VISIBLE = "FOAMING_VISIBLE"
    UNKNOWN_REVIEW = "UNKNOWN_REVIEW"


class JudgmentMode(StrEnum):
    RECOVERY = "RECOVERY"
    HOLD_BELOW_ZERO = "HOLD_BELOW_ZERO"
    HOLD_ABOVE_ZERO = "HOLD_ABOVE_ZERO"


class ResultState(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class BoundaryKind(StrEnum):
    OIL_AIR = "oil_air"
    FOAM_FRONT = "foam_front"


class EventType(StrEnum):
    ANALYSIS_START = "ANALYSIS_START"
    ANALYSIS_END = "ANALYSIS_END"
    COMPRESSOR_START = "COMPRESSOR_START"
    OIL_BOUNDARY_APPEARED_FROM_TOP = "OIL_BOUNDARY_APPEARED_FROM_TOP"
    OIL_BOUNDARY_APPEARED_FROM_BOTTOM = "OIL_BOUNDARY_APPEARED_FROM_BOTTOM"
    OIL_DROP_START = "OIL_DROP_START"
    MAXIMUM_OIL_LEVEL = "MAXIMUM_OIL_LEVEL"
    MINIMUM_OIL_LEVEL = "MINIMUM_OIL_LEVEL"
    ZERO_CROSS_UP = "ZERO_CROSS_UP"
    ZERO_CROSS_DOWN = "ZERO_CROSS_DOWN"
    ZERO_STABLE_RECOVERY = "ZERO_STABLE_RECOVERY"
    FULL_NO_INTERFACE_START = "FULL_NO_INTERFACE_START"
    EMPTY_NO_INTERFACE_START = "EMPTY_NO_INTERFACE_START"
    FOAM_START = "FOAM_START"
    FOAM_FRONT_RISING = "FOAM_FRONT_RISING"
    FOAM_REACH_ZERO = "FOAM_REACH_ZERO"
    FOAM_REACH_TOP = "FOAM_REACH_TOP"
    FOAM_END = "FOAM_END"
    LOW_CONFIDENCE_START = "LOW_CONFIDENCE_START"
    LOW_CONFIDENCE_END = "LOW_CONFIDENCE_END"
    DETECTION_LOST = "DETECTION_LOST"
    FOGGED_OR_GLARE = "FOGGED_OR_GLARE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    JUDGMENT_PASS = "JUDGMENT_PASS"
    JUDGMENT_FAIL = "JUDGMENT_FAIL"
